### ISSUE TITLE
Mitarbeiterstammdaten - ergänzende Informationen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#10]
Ist es möglich, die folgenden Informationen in den Mitarbeiterstammdaten aufzunehmen:
- privater PKW vorhanden: Ja/Nein
-Netzkarte vorhanden:  (hier sollte es möglich sein, die Art der Netzkarte einzutragen: z.B. "3Ringe" oder "ABB"
diese Informationen sollten auch in der Übersicht beim Mitarbeiter erscheinen. Für privater PKW vorhanden könnten dann in der Übersicht stehen "PKW"; bei einer vorhandenen Netzkarte sollte in der Übersicht das erscheinen, was in den Stammdaten eingetragen wurde (also z.B. "3Ringe")

**Comment by sembritzki** [comment]
hier geht es weiter (Entschuldigung für das Submitten, ohne das ich fertig war):
- erweitertes Führungszeugnis und Erste Hilfe:
Können wir hier ein Datum hinterlegen, an dem das Führungszeugnis ausgestellt bzw. der Erste Hilfe Kurs abgelegt worden ist? Wenn das möglich ist, wäre es hilfreich, eine Warnfunktion zu erhalten, wenn das Führungszeugnis bzw. der Erste Hilfe Kurs älter als 2 Jahre sind

**Comment by chrbusch** [comment]
Alles erledigt!
