### ISSUE TITLE
Job Detailübersicht - Ergänzung um Wochentage möglich?

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#11]
Kann man rechts neben dem Datum den entsprechenden Wochentag (Montag bis Sonntag) zeigen? Das würde das Übertragen der Daten aus dem Tätigkeitsnachweis (TN) deutlich erleichtern.

**Comment by chrbusch** [comment]
Filemaker kann das besser VOR dem Tag, das ist erledigt
Bitte dieses und jedes Ticket mit "Close" schliessen, wenn Sie sich von der korrekten Funktion überzeugt haben.
