### ISSUE TITLE
Infos über Mitarbeiter (PKW, Netzkarte, Bemerkung) in der Übersicht zeigen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#12]
Ich glaube, man sieht in der Übersicht beim Mitarbeiter noch nicht, ob ein PKW vorhanden ist bzw. welche Netzkarte da ist - ist das richtig? Ich habe es bei Perihan Cok ausprobiert und keine Angabe gesehen:
<img width="249" alt="bildschirmfoto 2016-10-18 um 22 51 30" src="https://cloud.githubusercontent.com/assets/22297185/19495937/b15d6da8-9585-11e6-8b1a-2fc0a3a1b885.png">

Grundsätzlich bräuchten wir diese Info in der Übersicht sowie die Info, die bei den Mitarbeiterstammdaten im Feld "Bemerkung" eingetragen werden. Im alten Planning wurden diese Infos, insbesondere "Bemerkungen" in eine separate Zeile direkt unter den Kalenderdaten, die über den ganzen Bildschirm reichte, geschrieben. Das ist wahrscheinlich keine optimale Lösung. 

Wäre es möglich, in der Übersicht bei den Mitarbeiterdaten die folgenden Infos einzublenden:
"PKW" - falls ein PKW vorhanden
"3Ringe" - falls unter Netzkarte etwas eingetragen wurde? (dies Feld kann auf 6 Zeichen begrenzt werden)
Zusätzlich ein Feld, in dem die "Bemerkung" über die Länge des Feldes mit den Mitarbeiterinformationen auftaucht und über das man mit dem Cursor fahren kann, um den vollständigen Eintrag zu lesen? Hier muss keine Feldbeschreibung erfolgen (also statt "Bemerkung: nicht beim Kunden XY einsetzen" würde es reichen, wenn dort einfach etwas steht, sofern das Feld "Bemerkung" in den Stammdaten ausgewählt worden ist.

**Comment by chrbusch** [comment]
Ist jetzt links zu sehen

![bildschirmfoto 2016-10-19 um 08 41 10](https://cloud.githubusercontent.com/assets/1241899/19508153/de50b20a-95d7-11e6-9f64-7265dc0797cc.JPG)
