### ISSUE TITLE
Übersicht Kalendertage: freies Feld zum Schreiben einer sehr kurzen Anmerkung 

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#13]
Wäre es möglich, an jedem Kalendertag noch ein Feld mit einem freien manuellen Eintrag einzurichten?
Die Disposition hat es sich im alten Planning angewöhnt, über dem Kalendertag Infos zu schreiben, wenn irgendetwas zu beachten ist - zum Beispiel, wenn wir den Dienst nicht direkt vom Kunden, sondern von einem Kooperationspartner (ein anderer Personaldienstleister) erhalten. Diese Infos werden nicht ausgewertet und dienen alleine der kurzfristigen Information des Disponenten.
Anbei ein Beispiel aus den alten Planning:
<img width="744" alt="bildschirmfoto 2016-10-18 um 23 05 51" src="https://cloud.githubusercontent.com/assets/22297185/19496429/c3698692-9587-11e6-9038-7554cccc8a49.png">

**Comment by chrbusch** [comment]
So ein Feld gibt es doch schon, ganz rechts im Detailfenster.
Im Beispiel habe ich dort für 3 Tage xx, yy bzw. zz eingetragen, das erscheint dann auf der ÜL

![bildschirmfoto 2016-10-19 um 09 13 04](https://cloud.githubusercontent.com/assets/1241899/19508970/6a58f7f4-95dc-11e6-90f5-d8903210367c.JPG)

**Comment by sembritzki** [comment]
Perfekt - Sie haben recht, ich hatte Scheuklappen auf...Vielen Dank!
