### ISSUE TITLE
Übersicht: Infobutton rot/grün (Mitarbeiter ist/muss informiert werden) in Tagesfeld anlegen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#14]
Ist es möglich, dass man im Tagesfeld sieht, ob der Mitarbeiter für diesen Tag schon informiert worden ist?
zum Beispiel:
Info MA OK / Info Ma fehlt
Info KD OK / Info KD fehlt

Es ist wieder sehr wichtig, diese Info pro Kalendertag zu haben. Wäre es aber auch möglich, die "Info MA OK" und "Info KD OK" für den gesamten Job auf einmal auszulösen (nötig bei langen Jobs)?

**Comment by chrbusch** [comment]
Jetzt erscheint grün "MA√" oder schwarz "MA?", dito für Kunden

**Comment by sembritzki** [comment]
Das sieht sehr gut aus! 
...und ist es auch möglich, für den ganzen Job mit einem Klick MA und KD Info auf Grün zu setzen?

**Comment by chrbusch** [comment]
Ich habe ein Script geschrieben, mit dem man ganz allgemein ein Feld für alle Tage eines Jobs auf einen bestimmten Wert setzen kann; die beiden neuen Buttons 
![bildschirmfoto 2016-10-19 um 15 30 26](https://cloud.githubusercontent.com/assets/1241899/19520623/261ae5f4-9611-11e6-9841-12c35ce01c0c.JPG)
rechts oben sind nur zwei "Instanzen" hiervon.
Sie können also hier ganz ungeniert weitere Wünsche äußern..

**Comment by sembritzki** [comment]
Klasse! Für die MA-Info funktioniert es, für die Kundeninfo kommt noch eine Fehlermeldung:
<img width="867" alt="bildschirmfoto 2016-10-19 um 15 34 52" src="https://cloud.githubusercontent.com/assets/22297185/19520892/081f0160-9612-11e6-9955-6be7b66990ec.png">

**Comment by chrbusch** [comment]
fixed
