### ISSUE TITLE
Job für einen Mitarbeiter komplett löschen?

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#15]
Es wäre hilfreich, einen falsch angelegten Job komplett löschen zu können. Da wir bisher pro Job nur einen Mitarbeiter zugeordnet haben und es wohl auch dabei bleiben wird (also immer pro Job genau ein Mitarbeiter), könnte man auch einen ganzen Job, der fälschlich angelegt oder aber wegen sonstiger Umstände nicht zustande kommt, löschen.

Wenn es geht, sollte nicht jeder User diese Löschberechtigung haben (zum Löschen eines kompletten Jobs), sondern nur ausgewählte User (zum Beispiel die Teamleiter). Vor dem Löschen sollte noch einmal gefragt werden, ob dieser Job tatsächlich gelöscht werden soll.

**Comment by chrbusch** [comment]
Bei Jobs, denen kein Mitarbeiter zugeordnet ist, halte ich das für unkritisch; dort erscheint jetzt ein Reiter LöschButton (2. Reiter der Kundenmaske)
Das Weitere müssen wir besprechen!

![bildschirmfoto 2016-10-19 um 17 27 42](https://cloud.githubusercontent.com/assets/1241899/19525511/7ad3fee0-9621-11e6-965d-6e6b94f1d84c.JPG)

**Comment by sembritzki** [comment]
In der Anfangsphase wurde für Frau Cok ein unendlicher Job angelegt  - dieser muss nun irgendwie gelöscht werden.

**Comment by chrbusch** [comment]
Kein pProblem; was ist das Wunschergebnis, alle "Cok-Tage" frei von Job, Stunden usw?

**Comment by sembritzki** [comment]
Ja - alle Cok Tage sollen frei von allem sein!

**Comment by chrbusch** [comment]
erl.

**Comment by sembritzki** [comment]
Ja! Frei von allem!

Mit freundlichen Gruessen / Best Regards


Christoph Sembritzki
Geschäftsführer

--

Extra-Personalservice GmbH
Hauptverwaltung
Georgsplatz 1, D-20099 Hamburg
Fon:  +49 (40) 32 32 44 - 0
Fax:  +49 (40) 32 32 44 - 44
Mail: sembritzki@extra-team.de<mailto:sembritzki@extra-team.de>

www.extra-team.de<http://www.extra-team.de/> | www.the-extra-way-to-work.de<http://www.the-extra-way-to-work.de/>

Gesellschaft und Sitz: Extra-Personalservice GmbH, Georgsplatz 1, D-20099 Hamburg. Amtsgericht Hamburg | HRB 37358 | St.-Nr.: 48/760/02227 | USt-Id: DE 118534861
Geschäftsführer: Sebastian Lazay und Christoph Sembritzki


Von: chrbusch [mailto:notifications@github.com]
Gesendet: Montag, 24. Oktober 2016 13:33
An: chrbusch/ExtraTeam
Cc: Christoph Sembritzki | Extra; Assign
Betreff: Re: [chrbusch/ExtraTeam] Job für einen Mitarbeiter komplett löschen? (#15)


Kein pProblem; was ist das Wunschergebnis, alle "Cok-Tage" frei von Job, Stunden usw?

**Comment by sembritzki** [comment]
..Frau OK ist jetzt gelöscht. Es gibt aber noch mehr Mitarbeiter mit **unendlich** langen Jobs - zum Beispiel Martina Özkan. Gehe ich hier auf "Detailansicht Job" und dann auf "zum Job" und ändere dort das End-Datum passiert leider nichts:
<img width="842" alt="bildschirmfoto 2016-10-25 um 22 37 52" src="https://cloud.githubusercontent.com/assets/22297185/19703393/ed9a4682-9b03-11e6-90e9-e0b39c5bfb41.png">

**Comment by chrbusch** [comment]
Ist das auch erledigt durch die neue Option <Fortsetzen>?
Zur Zeit fragt das System für jeden Sa/So nach; wäre es besser, die EINMAL vor der Schleife zu tun, dann könnten Sie als "Anzahl Tage" ja auch 30 angeben und hätten nicht so viel Dialoge?

**Comment by sembritzki** [comment]
Bei der Jobverlängerung ist es besser, vor der Schleife zu fragen, ob Samstag und Sonntag dabei sein sollen.
Beim Löschen geht es darum, dass zum Beispiel der Job von Frau Özkan (Hamburg Team Pflege, siehe Screenshot in meinem letzten Kommentar) gelöscht werden können müssen.

**Comment by chrbusch** [comment]
Vorschlag für Löschfunktion: Im Mitarb.-kalender klickt man eine Zeile (ein Datum) an und klickt oben einen neuen Button
<Ab hier aus Job nehmen>
Dann werden alle späteren Tage desselben Mitarbeiters, die zum selben Job gehören, von diesem befreit.

Einverstanden?

**Comment by chrbusch** [comment]
Would you be so kind to answer my question...

**Comment by chrbusch** [comment]
Auf dem MA-Kalender habe ich den Button "Fts" = Fortsetzen umbenannt in "Ab hier…", und ein Dialog fragt, was geschehen soll; VORSICHTIG testen oder noch besser mir einen Fall nennen, wo ein MA aus einem Job gestrichen werden soll

![Uploading Bildschirmfoto 2016-11-03 um 10.35.16.JPG…]()

**Comment by sembritzki** [comment]
Wir haben die Funktion getestet - sie funktioniert leider nicht so richtig:
 Bsp. 1. Verlängerung des Einsatzes Hamdorf Ab 07.10.16 bis 10.10.16 mit Funktion „Ab hier verlängern“  ohne Belegung von Wochenende.                     
–-> Das Programm verlängert den Job nicht..
 
Bsp. 2. Löschen von Job-Tagen Hamdorf Ab 07.10.2016  bis 10.10.2016, 3 Tage sollen gelöscht werden mit Funktion „Ab hier löschen“                                          
–-> Das Programm löscht nur Job Tag  10.10.16, Sa.-und Sonntag bleiben weiterhin im System.
 
Bsp. 3. Verlängerung des Einsatzes Hamdorf Ab 01.11.2016 6 Tage Fortschreiben mit Funktion „Ab hier verlängern“ ohne Belegung von Wochenende                
–-> Das System hat den Job nur bis 07.11.2016  verlängert, sollte hier bis 09.11.2016 (für 6 Tage)verlängert werden.
 
Für die Beispiele habe ich unten Screenshots angehängt.

**Comment by sembritzki** [comment]
![beispiel 1 bild 3](https://cloud.githubusercontent.com/assets/22297185/19966737/6fe4b45e-a1cd-11e6-8be2-0c5d0425f7b5.png)
![beispiel 1 bild 1](https://cloud.githubusercontent.com/assets/22297185/19966741/72272184-a1cd-11e6-9dce-a7f3f73dc18d.png)
![beispiel 2 bild 1](https://cloud.githubusercontent.com/assets/22297185/19966750/7a902dfc-a1cd-11e6-9d93-882cae120594.png)

**Comment by chrbusch** [comment]
Hamdorf hat doch gar keinen Job ab 7.10.!
Bitte ein Beispiel vorbereiten, anhand dessen ich testen kann.

**Comment by sembritzki** [comment]
Dies ist für uns gerade der Testmitarbeiter. Ich habe wieder einen Job angelegt (vom 7.10. bis 17.10). Hier kann jetzt alles ausprobiert werden.

**Comment by chrbusch** [comment]
Löschne und Fortschreiben aht sofort tadellos geklappt, vllt. eine Fehlbedienung?
Ich schlage vor, dass Sie mich anrufen und wir das per TeamViewer gemeinsam machen
