### ISSUE TITLE
Übersicht: Anzeige Kalendertag

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#16]
Um ein einheitlicheres Layout zu erhalten, in dem die einzelnen Infos immer auf derselben Höhe sind, wäre es sinnvoll, die einzelnen Kalendertage immer gleich zu strukturieren.

Könnte man daher jeder Info eine maximale Anzahl Zeichen zuordnen? 
Könnte man jeder Info ein Feld innerhalb des Kalendertages zuweisen, das leer bleibt, wenn dort nichts eingetragen ist?
Für die Felder "Einsatzort" und "Bemerkung" könnte man die komplette Info anzeigen, wenn man mit dem Cursor darüber fährt.

**Comment by chrbusch** [comment]
Ich verstehe nicht ganz, was Sie meinen.  Sprechen Sie hier von der Ü-Liste oder dem Detailfenster? Und "Info" meint wohl "Datenfeld?"

E.Ort und Bem. sind auf der Ü-Liste kein separaten Felder, hier wird nur EIN zusammen gesetztes Formelfeld gezeigt.
Im Detailfenster hingegen zeigen beide bereits ihren ganzen Inhalt als "Tooltip".

Was die Ü-Liste als Tooltip zeigt, können wir komplett frei bestimmen, bitte am besten konkretes Beispiel nennen in der Art "Drexel am 17.10.2016, hier sollte erscheinen...."

**Comment by sembritzki** [comment]
Mir geht es um die Kalendertage. Hier sollten die einzelnen Informationen idealerweise immer auf einer Höhe sein:
Also (in idealer Reihenfolge, aber die Reihenfolge kann auch bleiben wie sie zur Zeit ist): 
Kundenname (Matchcode), 
Einsatzort
Einsatzbereich (diese Info aus dem Detailfenster wird noch gar nicht angezeigt)
Arbeitszeit (z.B.: 14:00-18:30)
geplante Arbeitsstunden ("Ist: X,X")
TN fehlt/OK
Info MA/KD
<img width="707" alt="bildschirmfoto 2016-10-20 um 11 26 01" src="https://cloud.githubusercontent.com/assets/22297185/19554267/1cc5088e-96b8-11e6-91f9-f0b342005939.png">

**Comment by sembritzki** [comment]
...und Bemerkung ganz unten

**Comment by chrbusch** [comment]
Einsatzbereich ist jetzt drauf, um den Rest kümmere ich mich demnächst.
Bezgl. des Einsatzortes lasse ich jetzt dessen KURZ-Namen zeigen, wenn es einen solchen gibt.

**Comment by chrbusch** [comment]
Dies ist alles erledigt, oder?!
