### ISSUE TITLE
Übersicht/Detailanzeige: Arbeitszeitangabe

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#17]
Wir benötigen noch die genaue Arbeitszeit pro Kalendertag in der Detailanzeige und am Kalendertag (zum Beispiel 12:30-18:00)

**Comment by chrbusch** [comment]
Wird das denn zZ schon irgendwo eingegeben?
Bitte mehr Details liefern, wie es funktionieren soll.

**Comment by sembritzki** [comment]
Man kann im Detailfenster den Beginn der Schicht angeben aber nicht das Ende. Beginn und Ende der Arbeitszeit sind vor allem für die Pflege wichtig und sollte daher auch im Übersichtsfenster und im Dienstplan angezeigt werden:
<img width="737" alt="bildschirmfoto 2016-10-20 um 08 30 56" src="https://cloud.githubusercontent.com/assets/22297185/19548563/ad9f24fc-969f-11e6-92e0-c50c1cd69c39.png">
<img width="429" alt="bildschirmfoto 2016-10-20 um 08 29 48" src="https://cloud.githubusercontent.com/assets/22297185/19548564/afac0738-969f-11e6-94d1-c280da033bc2.png">

**Comment by sembritzki** [comment]
Ergänzung:
Wird im Kalendertag eine Uhrzeit angezeigt ("Soll: 14:30h-20:00h"), so kommt diese wohl aus den Kundenstammdaten und nicht aus der Detailansicht:
<img width="869" alt="bildschirmfoto 2016-10-20 um 11 23 28" src="https://cloud.githubusercontent.com/assets/22297185/19554213/e44e1c2a-96b7-11e6-9eb8-95179a703e0e.png">

**Comment by chrbusch** [comment]
Im Dialogfenster für einen neuen Job werden nun Beginn und Endzeit abgefragt; diese können mit einem neuen Button im Detailfenster auf alle Tage übertragen, dann aber auch tagesweise bearbeitet werden.

![bildschirmfoto 2016-10-23 um 08 19 04](https://cloud.githubusercontent.com/assets/1241899/19624502/8d6511ae-98f9-11e6-81ef-870b3a37b583.JPG)

**Comment by chrbusch** [comment]
..und sind Ist-Zeiten eingetragen, so erscheinen diese auf der Ü-Liste.
![bildschirmfoto 2016-10-23 um 08 23 49](https://cloud.githubusercontent.com/assets/1241899/19624522/18f19f8a-98fa-11e6-80ff-9b6cb18ba06a.JPG)

**Comment by sembritzki** [comment]
Hier ist ein Bug entstanden: "für alle Tage" scheint nicht zu funktionieren.

**Comment by chrbusch** [comment]
Damit ich prüfen kann, bitte immer exakte Angaben zum betroffenen Datensatz, also hier Mitarbeiter + Datum

**Comment by sembritzki** [comment]
..geht doch!
