### ISSUE TITLE
Mitarbeiterstammdaten-Kalendariumfunktion bei Mobilnummer löschen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#21]
In den Mitarbeiterstammdaten steht hinter der Mobilnummer eine Kalenderfunktion. Bei der Plausibiltätsprüfung leuchtet das Mobilnummerfeld genauso wie das Geburtsdatumsfeld auf.
<img width="464" alt="bildschirmfoto 2016-10-20 um 14 33 52" src="https://cloud.githubusercontent.com/assets/22297185/19559930/6ba4e900-96d2-11e6-84a2-6c8e81fd8273.png">

**Comment by chrbusch** [comment]
Beides fixed
