### ISSUE TITLE
Funktion: "Tagesdaten bearbeiten" kann wohl gelöscht werden, da nun unnötig?

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#22]
<img width="516" alt="bildschirmfoto 2016-10-20 um 14 37 04" src="https://cloud.githubusercontent.com/assets/22297185/19560000/d8314a8c-96d2-11e6-98b9-a7e64386c562.png">

**Comment by chrbusch** [comment]
Right!
