### ISSUE TITLE
Kalendertag: Feld Bemerkung einfügen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#23]
Wenn für einen Kalendertag ein Job ausgewählt ist, kann eine Bemerkung eingetragen werden.
Ist kein Job ausgewählt, kann keine Bemerkung in den Kalendertag eingetragen werden.

Ist es möglich, für jeden Kalendertag eine freie Bemerkung - idealerweise direkt im Kalendertag ganz oben oder ganz unten - einzutragen? Hier würde zum Beispiel stehen: "1. Hilfe Termin" oder "XXXX" wenn der Mitarbeiter an diesem Tag nicht zur Verfügung steht.

Da wir nun am oberen Bildschirmrand keine Detailansicht mehr haben, dürfte das Kalenderblatt hierfür auch etwas höher werden.

**Comment by chrbusch** [comment]
>Wenn für einen Kalendertag ein Job ausgewählt ist, kann eine Bemerkung eingetragen werden.
Ist kein Job ausgewählt, kann keine Bemerkung in den Kalendertag eingetragen werden.

Never say never!
Es gibt nun einen neuen breiten Button, der die nächsten 21 Tage des MA zeigt, auch wenn diese unbelegt sind; dort kann man die Bemerkung füllen.

![bildschirmfoto 2016-10-20 um 22 18 34](https://cloud.githubusercontent.com/assets/1241899/19576433/48a2c24c-9713-11e6-89cd-cfc87b0cf364.JPG)
