### ISSUE TITLE
Mitarbeiterstammdaten: "Bemerkung" aus MA-Stammdaten muss in Übersicht gezeigt werden 

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#24]
Der Inhalt des Felds "Bemerkung" aus den Mitarbeiter-Stammdaten muss in der Übersicht angezeigt werden. Idealerweise unter den Mitarbeiterdaten am linken Rand. Gerne kann man hier auch mit einem Tooltip arbeiten.

**Comment by chrbusch** [comment]
Der Tooltip auf dem Feld mit dem MA-Namen enthält nun div. Infos, auch die Bemerk
![bildschirmfoto 2016-10-20 um 22 09 52](https://cloud.githubusercontent.com/assets/1241899/19576086/fbad5688-9711-11e6-874a-9cd134721479.JPG)
ungen
