### ISSUE TITLE
Kundenstammdaten - Mapviewer Funktion bei Einsatzort hinterlegter?

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#25]
Map-Funktion: Zur Zeit ist die MAP - Funktion für die Anschrift des Kunden hinterlegt. Sinnvoller wäre es, diese Funktion für den Einsatzort zur Verfügung zu haben. Ginge das?

**Comment by chrbusch** [comment]
Dies ist schon seit ein paar Tagen so! Aber der Button erscheint nur dann beim einem Einsatzort (r. neben der Strasse), wenn Ort, PLZ + Strasse gefüllt sind.
Bei "Auguste Viktoria Stiftung" steht aber zB die Strasse im Kurznamen, dann klappt es halt nicht:-))
