### ISSUE TITLE
Jobansicht: Mitarbeiter pro Job / pro Kunde

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#26]
Es werden keine Mitarbeiter pro Job angezeigt. Das ist auch nicht so wichtig, da wir ja gesagt hatten, das es pro Job exakt einen Mitarbeiter geben soll. Allerdings sieht jetzt die Menüführung verwirrend aus.

<img width="1003" alt="bildschirmfoto 2016-10-24 um 15 18 11" src="https://cloud.githubusercontent.com/assets/22297185/19647275/9a7ff4e4-99fd-11e6-9236-5cdd93779af4.png">

**Comment by chrbusch** [comment]
Erledigt
