### ISSUE TITLE
Jobverlängerung auf Knopfdruck

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#28]
Wenn ein Job zu Ende ist, wäre es klasse, diesen automatisch verlängern zu können. Bei der Funktion 
"3 Wochen dieses Mitarbeiters ab" werden die nächsten drei Wochen angezeigt. Könnte man eine solche Funktion erstellen, die automatisch den Job des Tages, an dem man diese Funktion ausgelöst hat, für die kommenden drei Wochen mit übernimmt?

**Comment by chrbusch** [comment]
Ist ja wohl durch das andere Ticket erledigt, oder?
