### ISSUE TITLE
Bemerkung an jedem Tag eintragbar

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#29]
...ist jetzt zwar durch das Feld "3 Wochen dieses Mitarbeiters ab " möglich. Leider geht dies aber nicht, wenn Sonderkunden ausgewählt sind.
<img width="990" alt="bildschirmfoto 2016-10-24 um 15 26 39" src="https://cloud.githubusercontent.com/assets/22297185/19647508/ae497dd2-99fe-11e6-9894-f35bed1cf2a9.png">

**Comment by chrbusch** [comment]
Auch dies ist jetzt möglich

**Comment by sembritzki** [comment]
An nicht belegten Tagen (zum Beispiel Team Pflege - Andreas Blehle - muss am Sonntag, 8.10., eine Bemerkung eingetragen werden. Öffne ich diesen Tag, so kann ich die Funktion "3 Wochen dieses MA ab" nicht betätigen und somit auch keine Bemerkung eintragen.

**Comment by chrbusch** [comment]
Nun ist es folgendermaßen umgebaut: Ist dem angeklickten Tag kein Job zugeordnet, so heißt die Option "Folgende 21 Tage" und hält, was sie verspricht.

![bildschirmfoto 2016-10-25 um 13 29 15](https://cloud.githubusercontent.com/assets/1241899/19684448/800a0860-9ab7-11e6-836c-8aac37c60ec3.JPG)
