### ISSUE TITLE
Job - Detailübersicht: gelöschte Tage anzeigen / wiederbelegbar machen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#30]
<img width="785" alt="bildschirmfoto 2016-10-24 um 15 32 20" src="https://cloud.githubusercontent.com/assets/22297185/19647588/364f51d4-99ff-11e6-9be4-79cda44d75af.png">

**Comment by sembritzki** [comment]
Wenn man einen Job bearbeitet, löscht man die Tage, die man nicht benötigt. Muss man dann später Bemerkungen eintragen, ist es etwas unübersichtlich, da die gelöschten Tage nicht zu sehen sind.
Auch ist ist wohl zur Zeit nicht möglich, einen vorher gelöschten Tag wieder zu belegen.
Im obigen Beispiel könnte es zum Beispiel nötig sein, einen Dienst von Montag, 24.10. zu tauschen und auf den Sonntag, 23.10., zu verlegen. Es könnte auch sein, dass ein zusätzlicher Dienst gemacht werden muss. Hier also zum Beispiel zusätzlich Samstag, der 22.10.

**Comment by chrbusch** [comment]
Um auch den gelöschten Tagen Eine Bemerkung zu teilen zu können, gibt es ja bereits den Button <Drei Wochen dieses Mitarbeiters...>, der auch die freien Tage zeigt.
Bezüglich der Billigung eines freien Tages würde ich gerne mit Ihnen sprechen. 
Wir könnten im Detail Fenster neben den besetzten Tagen einen kleinen Button <F> wie "Fortsetzen" platzieren, der einen Dialog zeigt: "Diesen Job auf die nächsten ... Tage übertragen, sofern diese noch nicht belegt sind."
Geben Sie nun zum Beispiel beim 3.11. den Wert "3" ein, so wird der Job auf die Tage  4., 5. +6.11.  übertragen, falls diese noch frei sind.
Wäre das schon ausreichend? Sie könnten allerdings dann nur einen Job fortsetzen, für den derselbe Mitarbeiter schon einen Arbeitstag hat; ich vermute, Sie brauchen das noch flexibler, aber das sollten wir telefonisch besprechen

**Comment by sembritzki** [comment]
"Geben Sie nun zum Beispiel beim 3.11. den Wert "3" ein, so wird der Job auf die Tage 4., 5. +6.11. übertragen, falls diese noch frei sind.
Wäre das schon ausreichend?" --> das müsste schon ausreichend sein!

**Comment by chrbusch** [comment]
Bitte den neuen Button <Fts> im Detailfenster testen.

![bildschirmfoto 2016-10-26 um 08 18 33](https://cloud.githubusercontent.com/assets/1241899/19715370/fedfc164-9b54-11e6-905e-4ec19850a259.JPG)
![bildschirmfoto 2016-10-26 um 08 18 43](https://cloud.githubusercontent.com/assets/1241899/19715376/0634abe6-9b55-11e6-80f1-f61eeeb9cea1.JPG)

![bildschirmfoto 2016-10-26 um 08 18 57](https://cloud.githubusercontent.com/assets/1241899/19715379/0ab1fb60-9b55-11e6-835e-6e9c46edafec.JPG)

**Comment by sembritzki** [comment]
Der Button "fts" funktioniert prima. Hier wäre es - wie ja schon von Ihnen bemerkt - sinnvoll, nicht jeden Samstag und Sonntag abzufragen, sondern als Schleife vorab nach der Belegung von Wochenenden zu fragen.
Ich fände es aber auch hilfreich, dass nach der Löschung einzelner Tage im Job diese - auch nach Schließen und Wiedereröffnen des Jobs- noch angezeigt werden (natürlich als nicht zu diesem Job gehörende Tage). Das würde die Jobübersicht übersichtlicher (sic!) machen. Wäre es möglich, auch die nicht belegten Tage in der Jobübersicht zu sehen?

**Comment by sembritzki** [comment]
...dies wäre wie die Funktion "DF Folgende 21 Tage", die Sie bereits für freie Tage eingefügt haben, auch für mit einem Job belegte Tage.

**Comment by chrbusch** [comment]
Guten Morgen, Ich bin nicht ganz sicher, ob wir hier "semantisch kompatibel" sind:
Unter Übersicht verstehe ich das, was im Programm "Übersichtsliste" heißt; aber ich denke, in ihrem Beitrag meinen Sie mit "Jobübersicht" das, was im Programm "Job-Detailmaske" heißt.
Beide Ausdrücke finde ich aber auch nicht besonders klar gewählt (von mir).
Wir sollten meines Erachtens Bezeichnungen wählen, aus denen ganz klar hervorgeht, dass das erste Fenster ein ganzes Team in Kalenderdarstellung präsentiert, und das zweite die zeitlich sortierte Liste für einen einzelnen Mitarbeiter ist.
Wie wäre es mit "Team-Kalender" und "Mitarbeiter-Kalender"?
Meines Erachtens würde dies auch die Anleitung für die Mitarbeiter klarer machen, und Ihren Wunsch, wenn ich ihn richtig verstanden habe, könnte man dann so formulieren:

Wechselt man vom Teamkalender über den Button <Fkt.> zum Mitarbeiterkalender, so sollen stets die 21 Tage ab dem angeklickten Datum angezeigt werden, auch wenn sie nicht zu dem für den ersten Tag erteilten Job gehören.

**Comment by chrbusch** [comment]
Nun zeigt das System auf dem Mitarb.-Kalender stets 21 Tage voraus; daher könnten dort nun auch mehrere Jobs angezeigt werden, weshalb ich die "KundenFarben" dort links mit anzeigen lasse.

**Comment by sembritzki** [comment]
Guten Morgen Herr Busch, Sie haben völlig Recht! 
"Team Kalender" für die Übersicht, die das ganze Team zeigt, ist sehr gut.
"Mitarbeiter Kalender" für eine Übersicht, die die einzelnen Tage des Mitarbeiters anzeigen, ist klasse.
"Wechselt man vom Teamkalender über den Button zum Mitarbeiterkalender, so sollen stets die 21 Tage ab dem angeklickten Datum angezeigt werden, auch wenn sie nicht zu dem für den ersten Tag erteilten Job gehören."--> das ist korrekt. Hintergrund ist, dass wir häufig tagweise planen, ausgehend vom aktuellen Tag.

**Comment by chrbusch** [comment]
Ist nun umgesetzt.
Und auf dem Mitarb.Kal. gibt es einen neuen kleinen Button...

![bildschirmfoto 2016-10-27 um 08 55 58](https://cloud.githubusercontent.com/assets/1241899/19757464/4b7dd03c-9c23-11e6-9f90-569fdeac35f0.JPG)

**Comment by chrbusch** [comment]
Kann dieses Issue geschlossen werden?
