### ISSUE TITLE
Tage im Job löschen geht nicht mehr

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#31]
<img width="984" alt="bildschirmfoto 2016-10-25 um 09 43 11" src="https://cloud.githubusercontent.com/assets/22297185/19676980/834a6a1c-9a97-11e6-89c5-f8e3f6835e6a.png">

**Comment by chrbusch** [comment]
Fehler gefunden+behoben, bitte erneut testen
