### ISSUE TITLE
Farben von Kunden in Übersicht werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#32]

**Comment by chrbusch** [comment]
Bitte IMMER konkretes Beispiel, am besten mit Bild; bei mir sind die Farben zu sehen

**Comment by sembritzki** [comment]
Hier sind zum Beispiel keine Kundenfarben zu sehen, obwohl für die Kunden Farben hinterlegt sind:
<img width="1333" alt="bildschirmfoto 2016-10-25 um 22 44 28" src="https://cloud.githubusercontent.com/assets/22297185/19703628/cb37fa48-9b04-11e6-9bd6-87534b57b4a4.png">
<img width="838" alt="bildschirmfoto 2016-10-25 um 22 45 02" src="https://cloud.githubusercontent.com/assets/22297185/19703630/ccb9b6ea-9b04-11e6-832a-0937843206e4.png">

**Comment by sembritzki** [comment]
und hier beim selben Kunden sind die Farben zu sehen:
<img width="919" alt="bildschirmfoto 2016-10-25 um 22 46 57" src="https://cloud.githubusercontent.com/assets/22297185/19703685/04631cb2-9b05-11e6-9946-6c07a950aac9.png">

**Comment by chrbusch** [comment]
Erledigt
