### ISSUE TITLE
Jobanlage: Bemerkung wird nicht mehr ins Feld Bemerkung, sondern ins Feld Kundenname geschrieben

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#34]
<img width="842" alt="bildschirmfoto 2016-10-25 um 10 10 20" src="https://cloud.githubusercontent.com/assets/22297185/19677829/6a44f790-9a9b-11e6-884e-8078ac04812d.png">
![Uploading Bildschirmfoto 2016-10-25 um 10.10.47.png…]()

**Comment by chrbusch** [comment]
Hier liegt ein Mißverständnis vor: 
Es gibt eine Bem. für den JOB, die wird oben hinter den Kundennamen geschrieben und ist gleich für alle Tage des Jobs.
Und es gibt eine Bem. für den MitarbeiterTag, die wird unten geschrieben und kann für alle Tage unterschiedlich sein.
Im Eingabedialog wird die EINE Bemerkung für den JOB erfragt.
Evt. brauchen wir die nicht beide?
