### ISSUE TITLE
Übersicht-Kalendertage: "TNfehlt" Info verschwindet scheinbar grundlos

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#35]
<img width="538" alt="bildschirmfoto 2016-10-25 um 11 15 04" src="https://cloud.githubusercontent.com/assets/22297185/19680069/85f7d3e6-9aa4-11e6-9231-125533a2171a.png">
<img width="793" alt="bildschirmfoto 2016-10-25 um 11 15 33" src="https://cloud.githubusercontent.com/assets/22297185/19680072/87ddf1b8-9aa4-11e6-9adb-286ecdd53ea4.png">

**Comment by chrbusch** [comment]
Hier brauche ich viel mehr Information!
Was genau ist geschehen?

**Comment by sembritzki** [comment]
Die Mitarbeiterin ist in Dresden Team Pflege angelegt. Wenn ich auf den 25.10. gehe und die Detailansicht öffne und dann "TN OK" ankreuze, erscheint "TN OK" wieder auf dem Kalenderblatt. 
Wenn ich anschließend dann "TN OK" wieder rausnehme, dann verschwindet die Anzeige wieder vom Kalenderblatt.

**Comment by chrbusch** [comment]
OK, verstande und erledig; diese Info soll allerdings für die Zukunft m.E. nie erscheinen, denn die TN kann ja wohl frühestens am Arbeits-Datum vorliegen, oder?!

**Comment by sembritzki** [comment]
Damit haben Sie natürlich völlig recht - und ich Trottel habe nicht gemerkt, dass diese Info immer dann verschwindet, wenn der Tag in der Zukunft liegt...
