### ISSUE TITLE
JobAnlage nicht mehr möglich

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#37]
Ich wollte die Funktion "Bemerkung" für den ganzen Job und den einzelnen Tag ausprobieren. Dabei ist mir aufgefallen, dass ich wohl grundsätzlich keine neuen Jobs mehr erstellen kann. Ich habe es für mehrere Tage und Mitarbeiter ausprobiert und immer dieselbe Fehlermeldung erhalten.
Als Beispiel hier der folgende Screenshot von Dresden Team Pflege:
![Uploading Bildschirmfoto 2016-10-25 um 22.16.51.png…]()
![Uploading Bildschirmfoto 2016-10-25 um 22.17.02.png…]()

**Comment by sembritzki** [comment]
<img width="628" alt="bildschirmfoto 2016-10-25 um 22 16 51" src="https://cloud.githubusercontent.com/assets/22297185/19702958/3225745e-9b02-11e6-9d2a-e310736d8fb3.png">
<img width="595" alt="bildschirmfoto 2016-10-25 um 22 17 02" src="https://cloud.githubusercontent.com/assets/22297185/19702960/35f01d1e-9b02-11e6-92ce-2f45c9cd5b98.png">

**Comment by chrbusch** [comment]
Blöder Tippfehler meinerseits im Script, ist korrigiert!
