### ISSUE TITLE
Feiertage eintragen 

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#38]
Ich habe im Supervisor Modus die Feiertage "Reformationstag" und "Buß-Bettag" angekreuzt. Bei der Übersicht "Dresden - Team Kita" erscheint leider kein Feiertag. Habe ich etwas falsch gemacht?
<img width="771" alt="bildschirmfoto 2016-10-28 um 09 27 25" src="https://cloud.githubusercontent.com/assets/22297185/19798408/2ce408b6-9cf1-11e6-9013-4ac67529b2a3.png">

**Comment by chrbusch** [comment]
Bislang waren die Standorte noch gar keinem Bundesland zugeordnet!
Hierfür habe ich jetzt ein Auswahlfeld für die Maske "Standort-Details" gemacht, dort r.o.
Wenn das ausgefüllt ist, müssen wir besprochen, was genau im TeamKalender gezeigt werden soll.

**Comment by sembritzki** [comment]
Bei den auszahlbaren ist es jetzt ausgewählt (Buchholz - Niedersachsen, Potsdam - Brandenburg, Lübeck-Schleswig-Holstein sind nicht ausgewählt).

**Comment by chrbusch** [comment]
Ich habe die Werteliste so ergänzt, dass alle relevanten Bundesländer auswählbar sind.
Wir sollten mal telefonieren und zu besprechen, wie das nun genau berücksichtigt werden soll.
Ab 12h hätte ich Zeit dafür
