### ISSUE TITLE
Bug in der Übersichtsliste bei Datensatz Hentsch,André

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#39]
...steuert man den Team-Kalender für Dresden Team kita an, wird Herr Hentsch ganz unten in der Übersichtsliste angezeigt. 
Wenn man sich jedoch die Übersichtsliste nur für Herrn Hentsch anzeigen lässt und dann den Button Team "alle Mitarbeiter des Teams anzeigen" auslöst , wird er korrekt in der Übersicht dargestellt.

Außerdem werden Job Std. in der Übersicht links nicht aufgeführt...

![bild_1_bug_uebersichtsliste_ds_hentsch](https://cloud.githubusercontent.com/assets/22297185/19807265/a37290c8-9d1f-11e6-8f26-6e1901c0a3c1.png)

![bild_2_bug_uebersichtsliste_ds_hentsch](https://cloud.githubusercontent.com/assets/22297185/19807269/a66f50c2-9d1f-11e6-862e-30c76e65b1be.png)

![bild_3_bug_uebersichtsliste_ds_hentsch](https://cloud.githubusercontent.com/assets/22297185/19807271/a8facd08-9d1f-11e6-8082-16d09ff2bc34.png)

**Comment by chrbusch** [comment]
Erledigt,
Bitte möglichst die neuen Namen verwenden, i.e. "teamKalender" und "MA-Kalender"

**Comment by sembritzki** [comment]
Vielen Dank!
Die Summation der Produktivstunden wird leider immer noch nicht gezeigt:
<img width="1271" alt="bildschirmfoto 2016-10-31 um 07 47 42" src="https://cloud.githubusercontent.com/assets/22297185/19846310/69a326c0-9f3e-11e6-84ae-93c3a722e257.png">
<img width="396" alt="bildschirmfoto 2016-10-31 um 07 47 15" src="https://cloud.githubusercontent.com/assets/22297185/19846312/6a96fcdc-9f3e-11e6-86eb-f4486430cf3e.png">
<img width="1037" alt="bildschirmfoto 2016-10-31 um 07 46 58" src="https://cloud.githubusercontent.com/assets/22297185/19846311/6a64285c-9f3e-11e6-9bd1-32b4ed3e51dd.png">

**Comment by chrbusch** [comment]
Das ist nun erledigt; das Serverscripts, welches nachts die notwendigen Datensätze erstellt, war noch nicht fertig.
Auch habe ich links beim Mitarbeiter das Feld "Letzter Arbeitstag" rechts neben dem "AV Beginn" platziert (weil einige auf "Ausgeschieden" stehen und man bislang nicht erkennen konnte, bis wann genau die arbeiten.)
