### ISSUE TITLE
Extra Logo

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#40]
Könnten Sie bitte das Logo auf der Seite des Hauptmenüs austauschen? Oder kann ich das auch selber (ich glaube, Sie hatten mit dies einmal gesagt)?
![team_mit linien_cmyk_300](https://cloud.githubusercontent.com/assets/22297185/19925519/970e9de8-a0f0-11e6-9264-c9f996eac463.jpg)

**Comment by chrbusch** [comment]
Erl.
