### ISSUE TITLE
Extra Team Logos auf der Übersichtsseite

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#41]
Ist es möglich, auf der Übersichtsseite die Teamlogos - oben rechts - einzufügen (Kita, Pflege und Office - Technik muss ich noch zuschicken)?
![kita_mit linien_cmyk_300](https://cloud.githubusercontent.com/assets/22297185/19925571/db30332e-a0f0-11e6-97ea-e5720508e263.jpg)
![office_mit linien_cmyk_300](https://cloud.githubusercontent.com/assets/22297185/19925578/df833dae-a0f0-11e6-8d0f-c19feb787843.jpg)

**Comment by chrbusch** [comment]
Auf der Team-Maske ist ein neues Feld "Team-Logo" und ein Button zur Auswahl des Bildes. Bitte KLEINE Bilder einsetzen, sonst wird alles langsam!
Also zB in PhotoShop klein rechnen auf 100x200 Pixel

**Comment by chrbusch** [comment]
Die obigen Logos habe ich stark verkleinert eingesetzt, evt. reicht das schon so?!

**Comment by sembritzki** [comment]
Das sieht sehr gut aus und reicht, vielen Dank!
Anbei noch die Logos für Pflege und Technik:
![pflege_mit linien_cmyk_300](https://cloud.githubusercontent.com/assets/22297185/19935037/fb3eb050-a118-11e6-8d8a-4578fb869ad8.jpg)
![extra-technik-logo](https://cloud.githubusercontent.com/assets/22297185/19935074/1e3a06ea-a119-11e6-8b2d-2f83c5d8c556.jpg)

**Comment by chrbusch** [comment]
Erledigt
