### ISSUE TITLE
Neue Niederlassung Leipzig (statt Buchholz)

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#42]
Die Niederlassung Buchholz (aus dem alten Planning) existiert nicht wirklich. Daher habe ich mich gefragt, ob wir diese Niederlassung in Leipzig umbenennen können?
Alternativ bräuchte ich eine neue Niederlassung Leipzig.

**Comment by chrbusch** [comment]
Habe es umbenannt, bitte prüfen.
