### ISSUE TITLE
Doch ein Bug(?) - 

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#45]
Beim Mitarbeiter Binboga werden die Tage zwischen dem 22.10. (Arbeitsbeginn) und dem 1.11. trotz Aktualisierung beim Mitarbeiter nicht angezeigt.

<img width="1361" alt="bildschirmfoto 2016-11-02 um 14 30 04" src="https://cloud.githubusercontent.com/assets/22297185/19930549/347c9af4-a109-11e6-8eac-0e4e1a02a31d.png">

**Comment by chrbusch** [comment]
Der MA wurde angelegt 14 Tage nach AV-Beginn, damit hatte ich nicht gerechnet.
Klickt man nun beim MA den großen Button <...aktualisieren>, so werden alle MA-Tage angelegt, egal wie lange zuvor er anfing.
