### ISSUE TITLE
Teamkalender: Ausgeschiedene Mitarbeiter im Zeitraum nach dem Ausscheiden nicht mehr anzeigen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#46]
Sobald ein Mitarbeiter ausgeschieden ist, sollte der Datensatz in einer Abfrage, die ausschließlich den Zeitraum nach Ausscheiden des Mitarbeiters, nicht mehr im Teamkalender angezeigt werden:
<img width="1069" alt="bildschirmfoto 2016-11-02 um 15 04 52" src="https://cloud.githubusercontent.com/assets/22297185/19931747/eafcec3a-a10d-11e6-86c1-de2c70679857.png">

**Comment by chrbusch** [comment]
Erledigt.
ich schlage noch diese schnell umzusetzende Sache vor:
Der TeamKalender zeigt ja nun r.o. das Team-Logo. Klick auf dieses Logo könnte erlauben, das Team zu wechseln, das verursacht max. 15 Minuten Arbeit.

**Comment by sembritzki** [comment]
Das ist eine gute Idee! Da die meisten Disponenten nur zwischen den Teams ihrer Niederlassung wechseln, wäre es noch hilfreicher, wenn man über diese Funktion nur zwischen den Teams einer Niederlassung wechseln kann (um Verwechslungen zu vermeiden).

**Comment by chrbusch** [comment]
So ist es jetzt!

![bildschirmfoto 2016-11-03 um 10 20 26](https://cloud.githubusercontent.com/assets/1241899/19960784/32044244-a1af-11e6-9506-7c38630e9bb3.JPG)
