### ISSUE TITLE
Teamkalender/Neueintritt Mitarbeiter: Anzeige Kalendertage bei Neueintritten verschoben

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#47]
Fallen in den Anzeigebereich des Teamkalenders Neueintritte, so werden diese nach links verschoben. Daher sind bei diesen Mitarbeiten die Kalendertage nicht mehr an den übrigen Mitarbeitern ausgerichtet.

Ist es möglich, die Tage vor dem Arbeitsbeginn als leere Kästen bzw. mit dem Vermerk "vor Arbeitsbeginn" anzuzeigen?
<img width="1029" alt="bildschirmfoto 2016-11-03 um 10 01 33" src="https://cloud.githubusercontent.com/assets/22297185/19960615/40cbd5cc-a1ae-11e6-9160-12b27b3d9bec.png">

**Comment by chrbusch** [comment]
Wenn Sie den breiten Button "Mitarb.-Monate+Tage aktualisieren" beim MA klicken, sollte das schon alles korrekt angezeigt werden. Ich versuche gerade heraus zu finden, warum der Server das nicht automatisch macht...

**Comment by chrbusch** [comment]
Sollte jetzt alles autom. klappen!
Bei neuen MA unbedingt einmal den großen Button klicken
