### ISSUE TITLE
JZ: obigen Job zuordnen - könnte entfallen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#48]
Die Funktion "JZ:obigen Job zuordnen" könnte doch eigentlich entfallen?
<img width="885" alt="bildschirmfoto 2016-11-03 um 10 20 38" src="https://cloud.githubusercontent.com/assets/22297185/19960785/332ec8a6-a1af-11e6-837a-4d984f3c6c7c.png">

**Comment by chrbusch** [comment]
Erl.
