### ISSUE TITLE
Fkt.: Job: neuer Job - Anlage eines Jobs in der Vergangenheit nicht möglich

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#5]
<img width="1440" alt="bildschirmfoto 2016-09-23 um 12 51 03" src="https://cloud.githubusercontent.com/assets/22297185/18783583/ce39e940-818c-11e6-8670-e85e6a445b37.png">
<img width="1440" alt="bildschirmfoto 2016-09-23 um 12 50 44" src="https://cloud.githubusercontent.com/assets/22297185/18783581/ce039cdc-818c-11e6-8cc3-711d5c9de6dd.png">
<img width="1440" alt="bildschirmfoto 2016-09-23 um 12 50 13" src="https://cloud.githubusercontent.com/assets/22297185/18783584/ce4025f8-818c-11e6-96bc-732c6fc7e139.png">

Bei der Anlage eines Jobs und der Vergangenheit erscheint "Datum umplausibel"

**Comment by chrbusch** [comment]
Ist erledigt!
Und wenn irgendwo das pLugin "xmChart" fehlt, meldet sich nun das Script zur Erstellung der Farbmarkierung mit einer kurzen Meldung.

**Comment by chrbusch** [comment]
Das procedere wäre jetzt so: Wenn Sie meine, dass Ihr Issue erledigt ist, setzen sie dieses auf "Closed". Jeder tut das bitte nur für die von IHM SELBST ERSTELLTEN issues.
cbu
