### ISSUE TITLE
vertragliche Monatsarbeitszeit eines Mitarbeiters kann sich ändern

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#51]
Es ist möglich, dass sich die monatliche Arbeitszeit eines Mitarbeiters ändert (allerdings ausschliesslich zum ersten eines Monats). Daher muss es möglich sein, die Monatsarbeitszeit eines Mitarbeiters ab einem bestimmten Monat zu ändern. Die Arbeitszeit für die Vormonate darf sich dabei nicht ändern, um die Monatsauswertung nicht zu verändern.

**Comment by chrbusch** [comment]
Sie können nun auf dem Reiter "MitarbeiterMonate" für jeden Monat eine eigenen Stundenzahl angeben. Für neu erstellte MitarbMonate wird der Wert genommen, der auf dem ersten Reiter für den MA eingegeben wurde.


![bildschirmfoto 2016-11-03 um 12 13 52](https://cloud.githubusercontent.com/assets/1241899/19963945/2f5f896c-a1bf-11e6-9ac4-25a1d1365552.JPG)
