### ISSUE TITLE
Controlling Übersicht - Rechtevergabe

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#52]
Ich würde gerne  Auswertungen auf einer separaten Controlling-Übersicht (Button "nicht belegt") sehen können. Auf dieser Übersicht sollte man die jeweilige Niederlassung und die Gesamtsicht des Unternehmens auswählen können.

Hier wäre es nach reiflicher Überlegung doch sinnvoll, den Usern Rechte zuteilen zu können:
- Erlaubnis, alle Niederlassungen
- Erlaubnis, bestimmte Niederlassungen sehen zu dürfen 
- Erlaubnis, die Gesamtauswertung über alle Niederlassungen sehen zu dürfen)

**Comment by chrbusch** [comment]
Ich denke, "Niederlassung" ist das, was im Programm "Standort" heißt.
Sie können nun auf der User-Maske anklicken, welche(n) Standort(e) ein User auswerten darf.
Die Gesamtansicht würde ich einfach auf die Rolle "Supervisor" beschränken, oder müssen das noch mehr User können?

**Comment by sembritzki** [comment]
Niederlassung = Standort   das wollte ich natürlich sagen!

Zugriff auf die Gesamtansicht sollten idealerweise auch mehrere Nutzer haben (zum Beispiel mein Kompagnon und auch Mitarbeiter aus der Hauptverwaltung)

**Comment by chrbusch** [comment]
Es gibt nun ein weiteres Ankreuzfeld bei den Usern, und hier u.a. "Alle Auswertungen" als Option.
Bleibt die Frage, wie "Produktivität" berechnet wird!

**Comment by sembritzki** [comment]
Stand unter #50 ;-) 
Produktivität = Fakturierte Stunden / (vertragliche Arbeitszeit - Urlaub unbezahlt - Krank unbezahlt)

**Comment by sembritzki** [comment]
Verzeihung: Korrektur:
Produktivität = Fakturierte Stunden / (vertragliche Arbeitszeit - Urlaub unbezahlt - Krank unbezahlt-fehlt entschuldigt)
