### ISSUE TITLE
Bug? Liste "User" kann von mir nicht bearbeitet werden

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#54]
Wenn ich über das Hauptmenü auf Supervisor auf User Liste klicke erhalte ich die Übersicht über alle User.

Rufe ich dann einen User auf, der nicht meiner ist (z.B. Sven Hansson), erscheint die Detailmaske von mir selbst.

Gehe ich dann über "Liste User" zurück, so sehe ich nur meinen eigenen User. Gehe ich dann auf "alle zeigen", sehe ich wieder alle User.

**Comment by sembritzki** [comment]
<img width="847" alt="bildschirmfoto 2016-11-03 um 13 50 35" src="https://cloud.githubusercontent.com/assets/22297185/19966556/8c639146-a1cc-11e6-9374-cffd3c732b5d.png">
<img width="979" alt="bildschirmfoto 2016-11-03 um 13 50 41" src="https://cloud.githubusercontent.com/assets/22297185/19966558/8dfb6a1a-a1cc-11e6-8453-d5aebebdccb6.png">

**Comment by chrbusch** [comment]
Fixed
