### ISSUE TITLE
Team Logos einfügen

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#55]
Leider schaffe ich / verstehe ich nicht, wie ich ein Logo in ein Team einfüge:
<img width="861" alt="bildschirmfoto 2016-11-03 um 14 15 08" src="https://cloud.githubusercontent.com/assets/22297185/19967307/06a536be-a1d0-11e6-9030-b6a592f49fc6.png">
<img width="687" alt="bildschirmfoto 2016-11-03 um 14 14 33" src="https://cloud.githubusercontent.com/assets/22297185/19967305/0673b38c-a1d0-11e6-9af6-c97354fc00ca.png">
<img width="864" alt="bildschirmfoto 2016-11-03 um 14 14 18" src="https://cloud.githubusercontent.com/assets/22297185/19967306/06a3827e-a1d0-11e6-9607-586b695eb2ac.png">

**Comment by chrbusch** [comment]
Einfach EIN MAL in das Feld klicken; danach den blauen Button klicken.

**Comment by sembritzki** [comment]
Mach ich und es erscheint folgendes Bild:
Klicke ich dann auf das "jpg" passiert nichts. Hineinziehen kann ich das jpg auch nicht. Was soll ich tun?
<img width="1103" alt="bildschirmfoto 2016-11-03 um 14 49 46" src="https://cloud.githubusercontent.com/assets/22297185/19968754/312abc28-a1d6-11e6-828e-95ca3d050137.png">

**Comment by chrbusch** [comment]
bitte das logo per email zu mir, dann tste ich das hier. Bei mir klappt alles!

**Comment by chrbusch** [comment]
Ich glaube, Sie versuchen viiiiel zu große Bilder einzusetzen. Diese sollten nicht nennenswerter größer sein als ihre Anzeige im Programm also etwa 200 x 100 Pixel.
Eines der Bilder, die Sie mir schickten, war 5 MB (!!) groß!

**Comment by sembritzki** [comment]
Stimmt! Habe ich leider nicht beachtet....
