### ISSUE TITLE
Summationsfehler - produktive Stunden

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#57]
Zur Zeit scheinen die Summen über den Job (SummKlass1) nicht richtig angezeigt zu werden. Falls das daran liegt, dass Sie gerade an der Summation arbeiten, dann ignorieren Sie diesen Punkt bitte.

Bei Sabine Akhtar (Team Pflege Hamburg) wird zum Beispiel die falsche Summe über den Monat Oktober gezogen:
tatsächlich eingetragen: 79 Stunden
summarisch angezeigt: 99 Stunden
<img width="1145" alt="bildschirmfoto 2016-11-08 um 21 47 06" src="https://cloud.githubusercontent.com/assets/22297185/20116632/53b9cea2-a5fd-11e6-8f48-9b189ef8cec5.png">

Aber insbesondere wenn man sich ungeplante Monate anschaut wie den Dezember, werden dort Stunden als "Job" gezeigt, die noch gar nicht eingetragen sind:
<img width="1362" alt="bildschirmfoto 2016-11-08 um 22 49 27" src="https://cloud.githubusercontent.com/assets/22297185/20118717/e3a1caa8-a605-11e6-8ac2-5198f35d83a1.png">

**Comment by chrbusch** [comment]
Das ist nicht ganz trivial!
Die 99 Std sind die korrekte Zahl für den November! Und wir haben ja November.
Und da der Anzeigebereich ja auch monats-übergreifend sein kann, fragt sich: Welche Summe soll dort angezeigt werden?

**Comment by chrbusch** [comment]
Ich mache es jetzt so: OEs wird der Monat des ERSTEN Anzeigetages summiert; und dieser Monat wird im Format "1610" oben mit angezeigt

![bildschirmfoto 2016-11-09 um 08 45 29](https://cloud.githubusercontent.com/assets/1241899/20130708/f6fcdc02-a658-11e6-9baa-2c92de5180da.JPG)
