### ISSUE TITLE
Feiertage - Behandlung der Feiertage

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#58]
Unterscheide zwischen Team Pflege und allen anderen Teams.
A) alle anderen Teams
Wenn ein Feiertag gesetzt wird, soll folgendes passieren
- im Teamkalender wird der Tage  mit "Feiertag" belegt
- im Teamkalender wird der Tag mit der Tagesarbeitszeit des Mitarbeiters belegt
- in der Stundensummation beim Mitarbeiter und im Teamkalender oben rechts wird eine neue Kategorie aufgemacht "Feiertage" (Abk. "Ftg"), in der die Stunden des Feiertags des Monats gezählt werden

A1) Jobanlage: Behandlung der Feiertage 
- Feiertage sollen wie Wochenenden behandelt werden. Wird ausgewählt "WE nicht belegen", so sollen auch Feiertage nicht belegt werden und vice versa.
- ist ein Feiertag angelegt und der Mitarbeiter soll/will doch an dem Tag arbeiten, so soll der Feiertag im Teamkalender für diesen Mitarbeiter gegen einen anderen Job austauschbar sein
 
B) Team Pflege
da es in der Pflege per Definition keine Feiertage gibt, sollen Feiertage bei Mitarbeitern der Teams Pflege überhaupt nicht berücksichtigt werden.

**Comment by chrbusch** [comment]
Nun werden unter dem Datum die Feiertage angezeigt - ist das so wunschgemäß?

![bildschirmfoto 2016-11-20 um 08 08 56](https://cloud.githubusercontent.com/assets/1241899/20461273/b0ed905a-aef8-11e6-877d-05cf81f422aa.JPG)

**Comment by sembritzki** [comment]
Zur Kennzeichnung der Feiertage ist dies erstmal ausreichend.
Jetzt müsste an diesen Feiertagen noch automatisch ein "Sonderkunde Feiertag" (in allen Teams außer Pflege) eingepflegt werden. Dieser "Sonderkunde Feiertag" muss als "Anzahl Stunden" die tägliche Arbeitszeit des Mitarbeiters erhalten. Leider brauchen wir dann auch noch eine zusätzliche Summationsklasse "Feiertage". Diese müsste auch im Teamkalender sowohl links beim Mitarbeiter als auch oben rechts bei der Stundenübersicht angezeigt werden.
