### ISSUE TITLE
Summations-Unplausibilitäten

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#59]
Da ich mit der Summenbildung noch immer nicht klarkomme, habe ich mir ein kleines (noch unvollständiges)  Team herausgesucht: Berlin - Team Office (KST 42).
Anzahl Mitarbeiter: 5
Summe der vertraglichen Arbeitszeit (auch alles korrekt eingegeben): 
Behr: 130
Blum: 151,7
Filter: 108,3
Hiti: 151,7
Reichardt: 40
Summe: 581,7

Zahl der fakturierte Stunden: 112 (lediglich bei Behr sind die Stunden bislang eingetragen); Krank,Urlaub, AZK sind nicht eingetragen.
"Soll-Std.-obiges"  müsste demnach sein: 581,7 - 112 = 469,7
Angezeigt werden aber 621,35

Auch ist mir aufgefallen, dass sich das Ergebnis nicht ändert, wenn ich die Arbeitszeit eines Mitarbeiters ändere (mit "Aktualisierung") (siehe letztes Bild: Arbeitszeit Blum auf 100h reduziert, Summe unverändert).
<img width="1249" alt="bildschirmfoto 2016-11-15 um 21 33 53" src="https://cloud.githubusercontent.com/assets/22297185/20322986/518d766e-ab7b-11e6-83c5-df4eff5d40a2.png">

<img width="1283" alt="bildschirmfoto 2016-11-15 um 21 31 15" src="https://cloud.githubusercontent.com/assets/22297185/20322895/0100996a-ab7b-11e6-8d0b-e44e75ab59c2.png">
<img width="411" alt="bildschirmfoto 2016-11-15 um 21 31 36" src="https://cloud.githubusercontent.com/assets/22297185/20322897/01526704-ab7b-11e6-8646-0dfbec3e6577.png">
<img width="319" alt="bildschirmfoto 2016-11-15 um 21 31 50" src="https://cloud.githubusercontent.com/assets/22297185/20322896/01314060-ab7b-11e6-9c33-712b1988540b.png">

**Comment by chrbusch** [comment]
Vorschlag für Montag: Sie erstellen vorher ein "TEST-Team Hamburg"
Da tun wir zwei MA rein, Test1 und Test2
Dann können wir alles schmerzfrei testen; auch zB zwischendurch das Fel "Feiertage ignorieren?" umschalten usw.
Bei 2 MA und wenigen Jobs können wir dann problemlos im Kopf ausrechnen, was die korrekten Summen wären und ggfs. die Formeln anpassen.
Einverstanden?

**Comment by sembritzki** [comment]
Einverstanden - bereite ich sofort vor!
