### ISSUE TITLE
Kundenanlage: Ergänzung um Plausibilitätsprüfung (doppelte Kundennummer)

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#6]
Bei der Kundenanlage sollte geprüft werden, ob ein Kundendatensatz bereits angelegt worden ist.

**Comment by chrbusch** [comment]
OK, bitte ausprobieren!

![bildschirmfoto 2016-09-24 um 10 46 51](https://cloud.githubusercontent.com/assets/1241899/18807331/5976ef00-8244-11e6-901d-a3b3dd3da37d.JPG)
![bildschirmfoto 2016-09-24 um 10 47 32](https://cloud.githubusercontent.com/assets/1241899/18807334/5c1343f8-8244-11e6-9df8-a2e2dd56a654.JPG)
