### ISSUE TITLE
Kundenstammdaten - Farbzuordnung--> Möglichkeit, einem Einsatzort Farbe/Muster zuzuordnen?

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#60]
Aus Berlin kam der Wunsch, im Teamkalender die Einsätze auch nach Einsatzort unterscheiden zu können. 

Idealerweise könnte man das tun, indem man über die Kundenfarbe ein je nach Einsatzort unterschiedliches Muster bzw. einen hinterlegten Buchstaben/eine Zahl legt. 

Bei einem Kunden scheint es so zu sein, dass wir ein Muster bzw. ein "D" ausgewählt haben. Ich habe aber keine Idee, wie das ging (siehe Fotos).

<img width="1075" alt="bildschirmfoto 2016-11-18 um 12 49 15" src="https://cloud.githubusercontent.com/assets/22297185/20429271/dfb2d2d6-ad8d-11e6-9398-519c24e520a7.png">
<img width="951" alt="bildschirmfoto 2016-11-18 um 12 49 32" src="https://cloud.githubusercontent.com/assets/22297185/20429272/e08af102-ad8d-11e6-9ffe-b7dd0d60b98b.png">

**Comment by chrbusch** [comment]
Bitte schicken Sie mir für die Einsatzorte eines Kunden mal ein Set von solchen Bildern, KLEINE Dateien in der Größe, in der sie angezeigt werden.

**Comment by chrbusch** [comment]
Sie können nun aber auch selbst beim Einsatzort Bilder einsetzen in ein neues Feld; ERST den Cursor in das Bildfeld setzen, DANACH den Button klicken

![bildschirmfoto 2016-11-20 um 09 26 40](https://cloud.githubusercontent.com/assets/1241899/20461612/884a9610-af03-11e6-883d-d7d72cbbfe08.JPG)

**Comment by sembritzki** [comment]
Haben wir schon ausprobiert - funktioniert super! Vielen Dank!
