### ISSUE TITLE
Tausch - fast perfekt, nur die Bemerkung "TSv"MA-Name" bzw. "TSvMA-Name" fehlt

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#61]
der Tausch funktioniert jetzt fast perfekt. Lediglich das Feld "Bemerkung" im Mitarbeiterkalender wird nicht ausgefüllt. 
Idealerweise sollte beim abgebenden Mitarbeiter stehen:
 "TSn "Mitarbeitername des übernehmenden Mitarbeiters" " 
und beim übernehmenden Mitarbeiter:
"TSv "Mitarbeitername des abgebenden Mitarbeiters" "

**Comment by chrbusch** [comment]
..sollte jetzt auch so sein, bitte testen

**Comment by sembritzki** [comment]
Jetzt perfekt!
