### ISSUE TITLE
Mitarbeiterkalender - Funktion "Neuer Job" - fast perfekt

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#62]
Die Anlage eines neuen Jobs über die Funktion "Neuer Job" im Mitarbeiterkalender  funktioniert grundsätzlich.

Allerdings öffnet sich nach dem Abschluss der Jobeingabe ein Kalender in Form eines Mitarbeiterkalenders, der alle viele verschiedene nicht relevante Datensätze enthält, beginnend ca. 2 Wochen vor dem neuen Job. Diesen Kalender kann man nicht schließen. Man kann diese Ansicht nur schließen, indem man das ganze Programm beendet.

Der Job selber ist aber korrekt angelegt und bleibt auch im System, nachdem man das Programm geschlossen hat.
<img width="1163" alt="bildschirmfoto 2016-11-29 um 12 17 17" src="https://cloud.githubusercontent.com/assets/22297185/20707930/e221481a-b62d-11e6-8356-69193860c341.png">

**Comment by chrbusch** [comment]
...ich wiess, das ist noch nicht fertig!
habe jetzt Meeting, danach geht es weiter.
Am besten auf meine Freigabe warten

**Comment by chrbusch** [comment]
habe ich verbessert; ist das jetzt in Ordnung so?

**Comment by sembritzki** [comment]
In Ordnung - vielen Dank!
