### ISSUE TITLE
Teamkalender: Summe Job beim Mitarbeiter und der Summton

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#64]
Im Team Kita Dresden wurde bei einem Job vergessen, die Arbeitsstunden einzutragen. Dies habe ich dann im Mitarbeiterkalender nachgeholt. Danach habe ich im Teamkalender auf "Aktualisieren" gedrückt - trotzdem werden die Stunden des Jobs weder beim Mitarbeiter als "Job" angezeigt noch in der Summenübersicht des Teamkalenders.
<img width="828" alt="bildschirmfoto 2016-12-01 um 12 05 54" src="https://cloud.githubusercontent.com/assets/22297185/20791756/daaa2114-b7be-11e6-86f8-ab5107557dcc.png">

**Comment by chrbusch** [comment]
Sollte jetzt klappen, zumindest mit Klick auf <Aktualisieren>
Wäre es nicht sinnvoll, eine Plausib.-Prüfung für die Dialogbox "Neuer Job" zu definieren? M.E. müssen alle Felder außer der Bemerkung gefüllt werden, und zB für die AnzahlStunden könnten man fordern einen Wert zwischen 1 und 9 Stunden, oder?

**Comment by sembritzki** [comment]
Klappt - vielen Dank!
Bei der Jobeingabe wäre eine Plausibilitätsprüfung bei der Anzahl Stunden sinnvoll, die übrigen Felder könnten auch frei bleiben.

**Comment by chrbusch** [comment]
Plausibilitätsprüfung bei der Anzahl Stunden gibt es nun
