### ISSUE TITLE
xmChart - wir benötigen ein Installationspaket

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#7]
für die Einbindung des xmCHART-Plugins wird dass xmCHART Installationspaket benötigt. Es reicht nicht aus, die Plugindatei in das Programmverzeichnis einzufügen.

Die korrekte Installation erfolgt so:

1.	xmCHART Installationtspaket starten, hierbei öffnet sich FM-Pro
2.	Zielort für Filemaker Pro Client und Server wählen und starten

Eine DEMO Version von xmCHART, kann unter folgender Adresse runtergeladen werden http://www.x2max.com/download/

**Comment by chrbusch** [comment]
Es reicht m.E: vollkommen aus, das Plugin in den "Extensions"-Ordner zu ziehen und FM neu zu starten.
Auf jeden Fall wird aus der Demoversion die Vollversion durch eine in meinem Programm erfolgende Registrierung.
