### ISSUE TITLE
Kundenanlage - Vereinfachung Anlage und Anschrift Einsatzorte

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#8]
Kundennummer:
Bei der Neuanlage eine Kunden wird nach der Kundennummer gefragt. Diese wird nicht automatisch in das Feld "Kundennummer" übernommen. Wäre dies möglich?

Klasse:
Da Sonderkunden (Unproduktivitätstage) nur von mir angelegt werden sollten, ist eigentlich jeder Neukunde automatisch "Klasse 1" - kann man diese Einstellung als Default hinterlegen?

Einsatzort:
Hier wäre noch die Anschrift (Strasse und Ort) des Einsatzortes nötig.

**Comment by sembritzki** [comment]
Map-Funktion: Zur Zeit ist die MAP - Funktion auf die Anschrift des Kunden hinterlegt. Sinnvoller wäre es, diese Funktion für den Einsatzort zur Verfügung zu haben. Ginge das?

**Comment by chrbusch** [comment]
Kundennummer:
Bei der Neuanlage eine Kunden wird nach der Kundennummer gefragt. Diese wird nicht automatisch in das Feld "Kundennummer" übernommen. Wäre dies möglich?

>Klasse:Da Sonderkunden (Unproduktivitätstage) nur von mir angelegt werden sollten, ist eigentlich jeder Neukunde automatisch "Klasse 1" - kann man diese Einstellung als Default hinterlegen?

Gute Idee, erledigt. Und das Feld zur ÄNDERUNG der Klasse ist nun unsichtbar, wenn man nicht Supervisor ist.

Einsatzort:
Hier wäre noch die Anschrift (Strasse und Ort) des Einsatzortes nötig.
Erledigt, auch gibt es jetzt dort einen Button <Map-Viewer>

**Comment by chrbusch** [comment]
>Bei der Neuanlage eine Kunden wird nach der Kundennummer gefragt. Diese wird nicht automatisch in das Feld "Kundennummer" übernommen. Wäre dies möglich?

Ist das denn immer die KUNDEN-Nr? Im Dialog steht ja "KdNr oder DebitorNr".
Wenn wir uns auf eine davon festlegen können, kann diese autom. eingetragen werden

**Comment by chrbusch** [comment]
Ich habe nun die KdNr und die DebNr als sortierbare Spalten auf die Kundenliste gelegt; die DebitorNr ist ja nicht eindeutig, also sollten wir m.E. nur nach der Kd Nr fragen und diese prüfen.

**Comment by sembritzki** [comment]
Das ist korrekt, die Kundennummer ist die entscheidende Nummer und kann nur einmal vergeben werden. 
Die Debitorennummer kann mehrfach vergeben werden (mehrere Kunden können dieselbe Debitorennummer haben - zB bei einem Großunternehmen mit mehreren Betrieben wie Daimler AG mit Betriebsstätten in Bremen und Stuttgart).
