### ISSUE TITLE
Mitarbeiterstammdaten - Plausibilitätskontrolle

### ISSUE THREAD

**Issue by sembritzki** [chrbusch/ExtraTeam#9]
Bei der Mitarbeiteranlage können Mitarbeiter versehentlich doppelt angelegt werden.
Ist es möglich, bei der Neuanlage des Mitarbeiters nach der Personalnummer zu fragen? Sollte schon eine identische Personalnummer existieren, dann sollte eine Neuanlage nicht möglich sein. Auch hier wäre es sinnvoll, die eingegebene Personalnummer direkt in die Stammdaten zu übernehmen.

Zur Info: es muss möglich sein, Mitarbeiter doppelt anzulegen, da wir häufig Mitarbeiter haben, die mehrfach bei uns arbeiten - bei der Wiedereinstellung des Mitarbeiters wird dann aber eine neue Personalnummer vergeben. Eine doppelte Personalnummer darf also nicht vergeben werden können

**Comment by chrbusch** [comment]
Script ist verbessert; und in der Tat gibt es V. Drexel bereits doppelt! Einer der beiden hat Jobs, der Andere nicht; letzteren habe ich gelöscht.
![bildschirmfoto 2016-10-20 um 07 57 32](https://cloud.githubusercontent.com/assets/1241899/19547900/55a1e676-969b-11e6-91e2-2d0e4ad4fdae.JPG)
![bildschirmfoto 2016-10-20 um 07 57 41](https://cloud.githubusercontent.com/assets/1241899/19547903/5909cdba-969b-11e6-9e05-c67d0de56e2a.JPG)
